package catalog

func DefaultIngredients() []IngredientInfo {
	return []IngredientInfo{
		{Name: "assam tea", Family: "tea", Tags: []string{"bold", "caffeinated", "classic"}, CaloriesPerUnit: 2, CaffeineMG: 45, SeasonalMonths: []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, Description: "malty black tea base"},
		{Name: "jasmine tea", Family: "tea", Tags: []string{"floral", "caffeinated", "fresh"}, CaloriesPerUnit: 2, CaffeineMG: 30, SeasonalMonths: []int{3, 4, 5, 6, 7, 8}, Description: "fragrant green tea base"},
		{Name: "oolong tea", Family: "tea", Tags: []string{"roasted", "caffeinated", "smooth"}, CaloriesPerUnit: 2, CaffeineMG: 35, SeasonalMonths: []int{1, 2, 9, 10, 11, 12}, Description: "rounded roasted tea base"},
		{Name: "earl grey tea", Family: "tea", Tags: []string{"citrus", "caffeinated", "aromatic"}, CaloriesPerUnit: 2, CaffeineMG: 42, SeasonalMonths: []int{1, 2, 3, 9, 10, 11, 12}, Description: "bergamot black tea"},
		{Name: "genmaicha", Family: "tea", Tags: []string{"roasted", "caffeinated", "grain"}, CaloriesPerUnit: 4, CaffeineMG: 20, SeasonalMonths: []int{1, 2, 3, 10, 11, 12}, Description: "green tea with roasted rice"},
		{Name: "hojicha", Family: "tea", Tags: []string{"roasted", "low-caffeine", "warm"}, CaloriesPerUnit: 3, CaffeineMG: 12, SeasonalMonths: []int{1, 2, 10, 11, 12}, Description: "deep roasted green tea"},
		{Name: "matcha", Family: "tea", Tags: []string{"umami", "high-caffeine", "green"}, CaloriesPerUnit: 12, CaffeineMG: 65, SeasonalMonths: []int{3, 4, 5, 6}, Description: "stone ground green tea"},
		{Name: "white tea", Family: "tea", Tags: []string{"delicate", "low-caffeine", "floral"}, CaloriesPerUnit: 2, CaffeineMG: 18, SeasonalMonths: []int{3, 4, 5}, Description: "delicate young leaf tea"},
		{Name: "rooibos", Family: "herbal", Tags: []string{"caffeine-free", "honey", "warm"}, CaloriesPerUnit: 2, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 10, 11, 12}, Description: "red bush herbal infusion"},
		{Name: "chamomile", Family: "herbal", Tags: []string{"caffeine-free", "floral", "calm"}, CaloriesPerUnit: 2, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 3, 10, 11, 12}, Description: "soft floral infusion"},
		{Name: "peppermint", Family: "herbal", Tags: []string{"caffeine-free", "cooling", "fresh"}, CaloriesPerUnit: 2, CaffeineMG: 0, SeasonalMonths: []int{5, 6, 7, 8}, Description: "cool mint infusion"},
		{Name: "hibiscus", Family: "herbal", Tags: []string{"caffeine-free", "tart", "red"}, CaloriesPerUnit: 5, CaffeineMG: 0, SeasonalMonths: []int{5, 6, 7, 8, 9}, Description: "bright tart flower"},
		{Name: "whole milk", Family: "dairy", Allergens: []string{"milk"}, Tags: []string{"creamy", "dairy"}, CaloriesPerUnit: 120, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, Description: "full dairy milk"},
		{Name: "oat milk", Family: "plant-milk", Allergens: []string{"gluten"}, Tags: []string{"creamy", "plant-based"}, CaloriesPerUnit: 90, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, Description: "smooth oat beverage"},
		{Name: "soy milk", Family: "plant-milk", Allergens: []string{"soy"}, Tags: []string{"nutty", "plant-based"}, CaloriesPerUnit: 80, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, Description: "balanced soy beverage"},
		{Name: "coconut milk", Family: "plant-milk", Allergens: []string{"tree-nut"}, Tags: []string{"tropical", "plant-based"}, CaloriesPerUnit: 95, CaffeineMG: 0, SeasonalMonths: []int{5, 6, 7, 8}, Description: "tropical coconut beverage"},
		{Name: "brown sugar", Family: "sweetener", Tags: []string{"caramel", "sweet"}, CaloriesPerUnit: 70, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, Description: "dark caramel sweetness"},
		{Name: "honey", Family: "sweetener", Tags: []string{"honey", "sweet"}, CaloriesPerUnit: 64, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, Description: "floral natural sweetness"},
		{Name: "stevia", Family: "sweetener", Tags: []string{"low-calorie", "sweet"}, CaloriesPerUnit: 0, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, Description: "zero calorie sweetness"},
		{Name: "peach", Family: "fruit", Tags: []string{"fruity", "summer", "sweet"}, CaloriesPerUnit: 35, CaffeineMG: 0, SeasonalMonths: []int{6, 7, 8}, Description: "ripe stone fruit"},
		{Name: "mango", Family: "fruit", Tags: []string{"fruity", "tropical", "sweet"}, CaloriesPerUnit: 45, CaffeineMG: 0, SeasonalMonths: []int{5, 6, 7, 8}, Description: "rich tropical fruit"},
		{Name: "strawberry", Family: "fruit", Tags: []string{"fruity", "berry", "bright"}, CaloriesPerUnit: 30, CaffeineMG: 0, SeasonalMonths: []int{3, 4, 5, 6}, Description: "bright red berry"},
		{Name: "lemon", Family: "fruit", Tags: []string{"citrus", "tart", "fresh"}, CaloriesPerUnit: 12, CaffeineMG: 0, SeasonalMonths: []int{4, 5, 6, 7, 8, 9}, Description: "sharp yellow citrus"},
		{Name: "lime", Family: "fruit", Tags: []string{"citrus", "tart", "tropical"}, CaloriesPerUnit: 10, CaffeineMG: 0, SeasonalMonths: []int{5, 6, 7, 8, 9}, Description: "aromatic green citrus"},
		{Name: "grapefruit", Family: "fruit", Tags: []string{"citrus", "bitter", "fresh"}, CaloriesPerUnit: 25, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 3, 11, 12}, Description: "bittersweet pink citrus"},
		{Name: "lychee", Family: "fruit", Tags: []string{"fruity", "floral", "tropical"}, CaloriesPerUnit: 40, CaffeineMG: 0, SeasonalMonths: []int{5, 6, 7}, Description: "perfumed tropical fruit"},
		{Name: "passion fruit", Family: "fruit", Tags: []string{"fruity", "tart", "tropical"}, CaloriesPerUnit: 35, CaffeineMG: 0, SeasonalMonths: []int{6, 7, 8, 9}, Description: "aromatic tart fruit"},
		{Name: "pear", Family: "fruit", Tags: []string{"fruity", "delicate", "autumn"}, CaloriesPerUnit: 40, CaffeineMG: 0, SeasonalMonths: []int{8, 9, 10, 11}, Description: "delicate orchard fruit"},
		{Name: "apple", Family: "fruit", Tags: []string{"fruity", "crisp", "autumn"}, CaloriesPerUnit: 45, CaffeineMG: 0, SeasonalMonths: []int{8, 9, 10, 11}, Description: "crisp orchard fruit"},
		{Name: "watermelon", Family: "fruit", Tags: []string{"fruity", "summer", "refreshing"}, CaloriesPerUnit: 30, CaffeineMG: 0, SeasonalMonths: []int{6, 7, 8}, Description: "juicy summer melon"},
		{Name: "tapioca pearls", Family: "topping", Tags: []string{"chewy", "classic"}, CaloriesPerUnit: 160, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, Description: "brown sugar chewy pearls"},
		{Name: "grass jelly", Family: "topping", Tags: []string{"herbal", "silky", "low-calorie"}, CaloriesPerUnit: 35, CaffeineMG: 0, SeasonalMonths: []int{5, 6, 7, 8, 9}, Description: "cool herbal jelly"},
		{Name: "aloe cubes", Family: "topping", Tags: []string{"refreshing", "crisp", "plant-based"}, CaloriesPerUnit: 25, CaffeineMG: 0, SeasonalMonths: []int{5, 6, 7, 8}, Description: "crisp aloe topping"},
		{Name: "red bean", Family: "topping", Tags: []string{"earthy", "sweet", "classic"}, CaloriesPerUnit: 110, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 3, 10, 11, 12}, Description: "soft sweetened beans"},
		{Name: "cheese foam", Family: "topping", Allergens: []string{"milk"}, Tags: []string{"savory", "creamy", "dairy"}, CaloriesPerUnit: 145, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, Description: "lightly salted milk foam"},
		{Name: "chia seeds", Family: "topping", Tags: []string{"seed", "fiber", "plant-based"}, CaloriesPerUnit: 55, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, Description: "hydrated nutrient seeds"},
		{Name: "ginger", Family: "spice", Tags: []string{"spicy", "warm", "aromatic"}, CaloriesPerUnit: 8, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 10, 11, 12}, Description: "warming fresh ginger"},
		{Name: "cinnamon", Family: "spice", Tags: []string{"spicy", "warm", "sweet"}, CaloriesPerUnit: 6, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 10, 11, 12}, Description: "sweet bark spice"},
		{Name: "sea salt", Family: "seasoning", Tags: []string{"savory", "mineral"}, CaloriesPerUnit: 0, CaffeineMG: 0, SeasonalMonths: []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, Description: "clean mineral salt"},
		{Name: "sparkling water", Family: "water", Tags: []string{"sparkling", "refreshing", "low-calorie"}, CaloriesPerUnit: 0, CaffeineMG: 0, SeasonalMonths: []int{5, 6, 7, 8, 9}, Description: "carbonated water"},
	}
}
