package catalog

import (
	"fmt"
	"sort"
	"strings"
	"tea17/internal/domain"
)

type DrinkTemplate struct {
	ID          string
	Name        string
	Category    string
	Description string
	Ingredients []string
	Tags        []string
	PriceCents  int
	ServingNote string
}

var drinkTemplates = []DrinkTemplate{
	{
		ID:          "template-001",
		Name:        "peach assam honey",
		Category:    "seasonal-1",
		Description: "peach paired with assam tea and honey for a balanced store-ready drink",
		Ingredients: []string{"assam tea", "peach", "honey"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  420,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-002",
		Name:        "mango assam brown sugar",
		Category:    "seasonal-1",
		Description: "mango paired with assam tea and brown sugar for a balanced store-ready drink",
		Ingredients: []string{"assam tea", "mango", "brown sugar"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  430,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-003",
		Name:        "strawberry assam stevia",
		Category:    "seasonal-1",
		Description: "strawberry paired with assam tea and stevia for a balanced store-ready drink",
		Ingredients: []string{"assam tea", "strawberry", "stevia"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  440,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-004",
		Name:        "lemon assam sparkling water",
		Category:    "seasonal-1",
		Description: "lemon paired with assam tea and sparkling water for a balanced store-ready drink",
		Ingredients: []string{"assam tea", "lemon", "sparkling water"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  450,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-005",
		Name:        "lime assam oat",
		Category:    "seasonal-1",
		Description: "lime paired with assam tea and oat milk for a balanced store-ready drink",
		Ingredients: []string{"assam tea", "lime", "oat milk"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  460,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-006",
		Name:        "grapefruit assam soy",
		Category:    "seasonal-1",
		Description: "grapefruit paired with assam tea and soy milk for a balanced store-ready drink",
		Ingredients: []string{"assam tea", "grapefruit", "soy milk"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  470,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-007",
		Name:        "lychee assam coconut",
		Category:    "seasonal-1",
		Description: "lychee paired with assam tea and coconut milk for a balanced store-ready drink",
		Ingredients: []string{"assam tea", "lychee", "coconut milk"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  480,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-008",
		Name:        "passion fruit assam peppermint",
		Category:    "seasonal-1",
		Description: "passion fruit paired with assam tea and peppermint for a balanced store-ready drink",
		Ingredients: []string{"assam tea", "passion fruit", "peppermint"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  490,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-009",
		Name:        "pear assam ginger",
		Category:    "seasonal-1",
		Description: "pear paired with assam tea and ginger for a balanced store-ready drink",
		Ingredients: []string{"assam tea", "pear", "ginger"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  500,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-010",
		Name:        "apple assam cinnamon",
		Category:    "seasonal-1",
		Description: "apple paired with assam tea and cinnamon for a balanced store-ready drink",
		Ingredients: []string{"assam tea", "apple", "cinnamon"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  510,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-011",
		Name:        "watermelon assam honey",
		Category:    "seasonal-1",
		Description: "watermelon paired with assam tea and honey for a balanced store-ready drink",
		Ingredients: []string{"assam tea", "watermelon", "honey"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  520,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-012",
		Name:        "hibiscus assam brown sugar",
		Category:    "seasonal-1",
		Description: "hibiscus paired with assam tea and brown sugar for a balanced store-ready drink",
		Ingredients: []string{"assam tea", "hibiscus", "brown sugar"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  530,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-013",
		Name:        "peach jasmine sparkling water",
		Category:    "seasonal-2",
		Description: "peach paired with jasmine tea and sparkling water for a balanced store-ready drink",
		Ingredients: []string{"jasmine tea", "peach", "sparkling water"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  445,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-014",
		Name:        "mango jasmine oat",
		Category:    "seasonal-2",
		Description: "mango paired with jasmine tea and oat milk for a balanced store-ready drink",
		Ingredients: []string{"jasmine tea", "mango", "oat milk"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  455,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-015",
		Name:        "strawberry jasmine soy",
		Category:    "seasonal-2",
		Description: "strawberry paired with jasmine tea and soy milk for a balanced store-ready drink",
		Ingredients: []string{"jasmine tea", "strawberry", "soy milk"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  465,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-016",
		Name:        "lemon jasmine coconut",
		Category:    "seasonal-2",
		Description: "lemon paired with jasmine tea and coconut milk for a balanced store-ready drink",
		Ingredients: []string{"jasmine tea", "lemon", "coconut milk"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  475,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-017",
		Name:        "lime jasmine peppermint",
		Category:    "seasonal-2",
		Description: "lime paired with jasmine tea and peppermint for a balanced store-ready drink",
		Ingredients: []string{"jasmine tea", "lime", "peppermint"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  485,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-018",
		Name:        "grapefruit jasmine ginger",
		Category:    "seasonal-2",
		Description: "grapefruit paired with jasmine tea and ginger for a balanced store-ready drink",
		Ingredients: []string{"jasmine tea", "grapefruit", "ginger"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  495,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-019",
		Name:        "lychee jasmine cinnamon",
		Category:    "seasonal-2",
		Description: "lychee paired with jasmine tea and cinnamon for a balanced store-ready drink",
		Ingredients: []string{"jasmine tea", "lychee", "cinnamon"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  505,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-020",
		Name:        "passion fruit jasmine honey",
		Category:    "seasonal-2",
		Description: "passion fruit paired with jasmine tea and honey for a balanced store-ready drink",
		Ingredients: []string{"jasmine tea", "passion fruit", "honey"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  515,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-021",
		Name:        "pear jasmine brown sugar",
		Category:    "seasonal-2",
		Description: "pear paired with jasmine tea and brown sugar for a balanced store-ready drink",
		Ingredients: []string{"jasmine tea", "pear", "brown sugar"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  525,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-022",
		Name:        "apple jasmine stevia",
		Category:    "seasonal-2",
		Description: "apple paired with jasmine tea and stevia for a balanced store-ready drink",
		Ingredients: []string{"jasmine tea", "apple", "stevia"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  535,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-023",
		Name:        "watermelon jasmine sparkling water",
		Category:    "seasonal-2",
		Description: "watermelon paired with jasmine tea and sparkling water for a balanced store-ready drink",
		Ingredients: []string{"jasmine tea", "watermelon", "sparkling water"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  545,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-024",
		Name:        "hibiscus jasmine oat",
		Category:    "seasonal-2",
		Description: "hibiscus paired with jasmine tea and oat milk for a balanced store-ready drink",
		Ingredients: []string{"jasmine tea", "hibiscus", "oat milk"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  555,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-025",
		Name:        "peach oolong coconut",
		Category:    "seasonal-3",
		Description: "peach paired with oolong tea and coconut milk for a balanced store-ready drink",
		Ingredients: []string{"oolong tea", "peach", "coconut milk"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  470,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-026",
		Name:        "mango oolong peppermint",
		Category:    "seasonal-3",
		Description: "mango paired with oolong tea and peppermint for a balanced store-ready drink",
		Ingredients: []string{"oolong tea", "mango", "peppermint"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  480,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-027",
		Name:        "strawberry oolong ginger",
		Category:    "seasonal-3",
		Description: "strawberry paired with oolong tea and ginger for a balanced store-ready drink",
		Ingredients: []string{"oolong tea", "strawberry", "ginger"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  490,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-028",
		Name:        "lemon oolong cinnamon",
		Category:    "seasonal-3",
		Description: "lemon paired with oolong tea and cinnamon for a balanced store-ready drink",
		Ingredients: []string{"oolong tea", "lemon", "cinnamon"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  500,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-029",
		Name:        "lime oolong honey",
		Category:    "seasonal-3",
		Description: "lime paired with oolong tea and honey for a balanced store-ready drink",
		Ingredients: []string{"oolong tea", "lime", "honey"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  510,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-030",
		Name:        "grapefruit oolong brown sugar",
		Category:    "seasonal-3",
		Description: "grapefruit paired with oolong tea and brown sugar for a balanced store-ready drink",
		Ingredients: []string{"oolong tea", "grapefruit", "brown sugar"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  520,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-031",
		Name:        "lychee oolong stevia",
		Category:    "seasonal-3",
		Description: "lychee paired with oolong tea and stevia for a balanced store-ready drink",
		Ingredients: []string{"oolong tea", "lychee", "stevia"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  530,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-032",
		Name:        "passion fruit oolong sparkling water",
		Category:    "seasonal-3",
		Description: "passion fruit paired with oolong tea and sparkling water for a balanced store-ready drink",
		Ingredients: []string{"oolong tea", "passion fruit", "sparkling water"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  540,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-033",
		Name:        "pear oolong oat",
		Category:    "seasonal-3",
		Description: "pear paired with oolong tea and oat milk for a balanced store-ready drink",
		Ingredients: []string{"oolong tea", "pear", "oat milk"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  550,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-034",
		Name:        "apple oolong soy",
		Category:    "seasonal-3",
		Description: "apple paired with oolong tea and soy milk for a balanced store-ready drink",
		Ingredients: []string{"oolong tea", "apple", "soy milk"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  560,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-035",
		Name:        "watermelon oolong coconut",
		Category:    "seasonal-3",
		Description: "watermelon paired with oolong tea and coconut milk for a balanced store-ready drink",
		Ingredients: []string{"oolong tea", "watermelon", "coconut milk"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  570,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-036",
		Name:        "hibiscus oolong peppermint",
		Category:    "seasonal-3",
		Description: "hibiscus paired with oolong tea and peppermint for a balanced store-ready drink",
		Ingredients: []string{"oolong tea", "hibiscus", "peppermint"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  580,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-037",
		Name:        "peach earl grey cinnamon",
		Category:    "seasonal-4",
		Description: "peach paired with earl grey tea and cinnamon for a balanced store-ready drink",
		Ingredients: []string{"earl grey tea", "peach", "cinnamon"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  495,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-038",
		Name:        "mango earl grey honey",
		Category:    "seasonal-4",
		Description: "mango paired with earl grey tea and honey for a balanced store-ready drink",
		Ingredients: []string{"earl grey tea", "mango", "honey"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  505,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-039",
		Name:        "strawberry earl grey brown sugar",
		Category:    "seasonal-4",
		Description: "strawberry paired with earl grey tea and brown sugar for a balanced store-ready drink",
		Ingredients: []string{"earl grey tea", "strawberry", "brown sugar"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  515,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-040",
		Name:        "lemon earl grey stevia",
		Category:    "seasonal-4",
		Description: "lemon paired with earl grey tea and stevia for a balanced store-ready drink",
		Ingredients: []string{"earl grey tea", "lemon", "stevia"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  525,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-041",
		Name:        "lime earl grey sparkling water",
		Category:    "seasonal-4",
		Description: "lime paired with earl grey tea and sparkling water for a balanced store-ready drink",
		Ingredients: []string{"earl grey tea", "lime", "sparkling water"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  535,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-042",
		Name:        "grapefruit earl grey oat",
		Category:    "seasonal-4",
		Description: "grapefruit paired with earl grey tea and oat milk for a balanced store-ready drink",
		Ingredients: []string{"earl grey tea", "grapefruit", "oat milk"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  545,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-043",
		Name:        "lychee earl grey soy",
		Category:    "seasonal-4",
		Description: "lychee paired with earl grey tea and soy milk for a balanced store-ready drink",
		Ingredients: []string{"earl grey tea", "lychee", "soy milk"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  555,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-044",
		Name:        "passion fruit earl grey coconut",
		Category:    "seasonal-4",
		Description: "passion fruit paired with earl grey tea and coconut milk for a balanced store-ready drink",
		Ingredients: []string{"earl grey tea", "passion fruit", "coconut milk"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  565,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-045",
		Name:        "pear earl grey peppermint",
		Category:    "seasonal-4",
		Description: "pear paired with earl grey tea and peppermint for a balanced store-ready drink",
		Ingredients: []string{"earl grey tea", "pear", "peppermint"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  575,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-046",
		Name:        "apple earl grey ginger",
		Category:    "seasonal-4",
		Description: "apple paired with earl grey tea and ginger for a balanced store-ready drink",
		Ingredients: []string{"earl grey tea", "apple", "ginger"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  585,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-047",
		Name:        "watermelon earl grey cinnamon",
		Category:    "seasonal-4",
		Description: "watermelon paired with earl grey tea and cinnamon for a balanced store-ready drink",
		Ingredients: []string{"earl grey tea", "watermelon", "cinnamon"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  595,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-048",
		Name:        "hibiscus earl grey honey",
		Category:    "seasonal-4",
		Description: "hibiscus paired with earl grey tea and honey for a balanced store-ready drink",
		Ingredients: []string{"earl grey tea", "hibiscus", "honey"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  605,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-049",
		Name:        "peach genmaicha stevia",
		Category:    "seasonal-1",
		Description: "peach paired with genmaicha and stevia for a balanced store-ready drink",
		Ingredients: []string{"genmaicha", "peach", "stevia"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  520,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-050",
		Name:        "mango genmaicha sparkling water",
		Category:    "seasonal-1",
		Description: "mango paired with genmaicha and sparkling water for a balanced store-ready drink",
		Ingredients: []string{"genmaicha", "mango", "sparkling water"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  530,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-051",
		Name:        "strawberry genmaicha oat",
		Category:    "seasonal-1",
		Description: "strawberry paired with genmaicha and oat milk for a balanced store-ready drink",
		Ingredients: []string{"genmaicha", "strawberry", "oat milk"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  540,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-052",
		Name:        "lemon genmaicha soy",
		Category:    "seasonal-1",
		Description: "lemon paired with genmaicha and soy milk for a balanced store-ready drink",
		Ingredients: []string{"genmaicha", "lemon", "soy milk"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  550,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-053",
		Name:        "lime genmaicha coconut",
		Category:    "seasonal-1",
		Description: "lime paired with genmaicha and coconut milk for a balanced store-ready drink",
		Ingredients: []string{"genmaicha", "lime", "coconut milk"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  560,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-054",
		Name:        "grapefruit genmaicha peppermint",
		Category:    "seasonal-1",
		Description: "grapefruit paired with genmaicha and peppermint for a balanced store-ready drink",
		Ingredients: []string{"genmaicha", "grapefruit", "peppermint"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  570,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-055",
		Name:        "lychee genmaicha ginger",
		Category:    "seasonal-1",
		Description: "lychee paired with genmaicha and ginger for a balanced store-ready drink",
		Ingredients: []string{"genmaicha", "lychee", "ginger"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  580,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-056",
		Name:        "passion fruit genmaicha cinnamon",
		Category:    "seasonal-1",
		Description: "passion fruit paired with genmaicha and cinnamon for a balanced store-ready drink",
		Ingredients: []string{"genmaicha", "passion fruit", "cinnamon"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  590,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-057",
		Name:        "pear genmaicha honey",
		Category:    "seasonal-1",
		Description: "pear paired with genmaicha and honey for a balanced store-ready drink",
		Ingredients: []string{"genmaicha", "pear", "honey"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  600,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-058",
		Name:        "apple genmaicha brown sugar",
		Category:    "seasonal-1",
		Description: "apple paired with genmaicha and brown sugar for a balanced store-ready drink",
		Ingredients: []string{"genmaicha", "apple", "brown sugar"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  610,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-059",
		Name:        "watermelon genmaicha stevia",
		Category:    "seasonal-1",
		Description: "watermelon paired with genmaicha and stevia for a balanced store-ready drink",
		Ingredients: []string{"genmaicha", "watermelon", "stevia"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  620,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-060",
		Name:        "hibiscus genmaicha sparkling water",
		Category:    "seasonal-1",
		Description: "hibiscus paired with genmaicha and sparkling water for a balanced store-ready drink",
		Ingredients: []string{"genmaicha", "hibiscus", "sparkling water"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  630,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-061",
		Name:        "peach hojicha soy",
		Category:    "seasonal-2",
		Description: "peach paired with hojicha and soy milk for a balanced store-ready drink",
		Ingredients: []string{"hojicha", "peach", "soy milk"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  545,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-062",
		Name:        "mango hojicha coconut",
		Category:    "seasonal-2",
		Description: "mango paired with hojicha and coconut milk for a balanced store-ready drink",
		Ingredients: []string{"hojicha", "mango", "coconut milk"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  555,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-063",
		Name:        "strawberry hojicha peppermint",
		Category:    "seasonal-2",
		Description: "strawberry paired with hojicha and peppermint for a balanced store-ready drink",
		Ingredients: []string{"hojicha", "strawberry", "peppermint"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  565,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-064",
		Name:        "lemon hojicha ginger",
		Category:    "seasonal-2",
		Description: "lemon paired with hojicha and ginger for a balanced store-ready drink",
		Ingredients: []string{"hojicha", "lemon", "ginger"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  575,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-065",
		Name:        "lime hojicha cinnamon",
		Category:    "seasonal-2",
		Description: "lime paired with hojicha and cinnamon for a balanced store-ready drink",
		Ingredients: []string{"hojicha", "lime", "cinnamon"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  585,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-066",
		Name:        "grapefruit hojicha honey",
		Category:    "seasonal-2",
		Description: "grapefruit paired with hojicha and honey for a balanced store-ready drink",
		Ingredients: []string{"hojicha", "grapefruit", "honey"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  595,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-067",
		Name:        "lychee hojicha brown sugar",
		Category:    "seasonal-2",
		Description: "lychee paired with hojicha and brown sugar for a balanced store-ready drink",
		Ingredients: []string{"hojicha", "lychee", "brown sugar"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  605,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-068",
		Name:        "passion fruit hojicha stevia",
		Category:    "seasonal-2",
		Description: "passion fruit paired with hojicha and stevia for a balanced store-ready drink",
		Ingredients: []string{"hojicha", "passion fruit", "stevia"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  615,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-069",
		Name:        "pear hojicha sparkling water",
		Category:    "seasonal-2",
		Description: "pear paired with hojicha and sparkling water for a balanced store-ready drink",
		Ingredients: []string{"hojicha", "pear", "sparkling water"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  625,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-070",
		Name:        "apple hojicha oat",
		Category:    "seasonal-2",
		Description: "apple paired with hojicha and oat milk for a balanced store-ready drink",
		Ingredients: []string{"hojicha", "apple", "oat milk"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  635,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-071",
		Name:        "watermelon hojicha soy",
		Category:    "seasonal-2",
		Description: "watermelon paired with hojicha and soy milk for a balanced store-ready drink",
		Ingredients: []string{"hojicha", "watermelon", "soy milk"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  645,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-072",
		Name:        "hibiscus hojicha coconut",
		Category:    "seasonal-2",
		Description: "hibiscus paired with hojicha and coconut milk for a balanced store-ready drink",
		Ingredients: []string{"hojicha", "hibiscus", "coconut milk"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  655,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-073",
		Name:        "peach matcha ginger",
		Category:    "seasonal-3",
		Description: "peach paired with matcha and ginger for a balanced store-ready drink",
		Ingredients: []string{"matcha", "peach", "ginger"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  570,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-074",
		Name:        "mango matcha cinnamon",
		Category:    "seasonal-3",
		Description: "mango paired with matcha and cinnamon for a balanced store-ready drink",
		Ingredients: []string{"matcha", "mango", "cinnamon"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  580,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-075",
		Name:        "strawberry matcha honey",
		Category:    "seasonal-3",
		Description: "strawberry paired with matcha and honey for a balanced store-ready drink",
		Ingredients: []string{"matcha", "strawberry", "honey"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  590,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-076",
		Name:        "lemon matcha brown sugar",
		Category:    "seasonal-3",
		Description: "lemon paired with matcha and brown sugar for a balanced store-ready drink",
		Ingredients: []string{"matcha", "lemon", "brown sugar"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  600,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-077",
		Name:        "lime matcha stevia",
		Category:    "seasonal-3",
		Description: "lime paired with matcha and stevia for a balanced store-ready drink",
		Ingredients: []string{"matcha", "lime", "stevia"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  610,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-078",
		Name:        "grapefruit matcha sparkling water",
		Category:    "seasonal-3",
		Description: "grapefruit paired with matcha and sparkling water for a balanced store-ready drink",
		Ingredients: []string{"matcha", "grapefruit", "sparkling water"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  620,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-079",
		Name:        "lychee matcha oat",
		Category:    "seasonal-3",
		Description: "lychee paired with matcha and oat milk for a balanced store-ready drink",
		Ingredients: []string{"matcha", "lychee", "oat milk"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  630,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-080",
		Name:        "passion fruit matcha soy",
		Category:    "seasonal-3",
		Description: "passion fruit paired with matcha and soy milk for a balanced store-ready drink",
		Ingredients: []string{"matcha", "passion fruit", "soy milk"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  640,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-081",
		Name:        "pear matcha coconut",
		Category:    "seasonal-3",
		Description: "pear paired with matcha and coconut milk for a balanced store-ready drink",
		Ingredients: []string{"matcha", "pear", "coconut milk"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  650,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-082",
		Name:        "apple matcha peppermint",
		Category:    "seasonal-3",
		Description: "apple paired with matcha and peppermint for a balanced store-ready drink",
		Ingredients: []string{"matcha", "apple", "peppermint"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  660,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-083",
		Name:        "watermelon matcha ginger",
		Category:    "seasonal-3",
		Description: "watermelon paired with matcha and ginger for a balanced store-ready drink",
		Ingredients: []string{"matcha", "watermelon", "ginger"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  670,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-084",
		Name:        "hibiscus matcha cinnamon",
		Category:    "seasonal-3",
		Description: "hibiscus paired with matcha and cinnamon for a balanced store-ready drink",
		Ingredients: []string{"matcha", "hibiscus", "cinnamon"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  680,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-085",
		Name:        "peach white brown sugar",
		Category:    "seasonal-4",
		Description: "peach paired with white tea and brown sugar for a balanced store-ready drink",
		Ingredients: []string{"white tea", "peach", "brown sugar"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  595,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-086",
		Name:        "mango white stevia",
		Category:    "seasonal-4",
		Description: "mango paired with white tea and stevia for a balanced store-ready drink",
		Ingredients: []string{"white tea", "mango", "stevia"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  605,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-087",
		Name:        "strawberry white sparkling water",
		Category:    "seasonal-4",
		Description: "strawberry paired with white tea and sparkling water for a balanced store-ready drink",
		Ingredients: []string{"white tea", "strawberry", "sparkling water"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  615,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-088",
		Name:        "lemon white oat",
		Category:    "seasonal-4",
		Description: "lemon paired with white tea and oat milk for a balanced store-ready drink",
		Ingredients: []string{"white tea", "lemon", "oat milk"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  625,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-089",
		Name:        "lime white soy",
		Category:    "seasonal-4",
		Description: "lime paired with white tea and soy milk for a balanced store-ready drink",
		Ingredients: []string{"white tea", "lime", "soy milk"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  635,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-090",
		Name:        "grapefruit white coconut",
		Category:    "seasonal-4",
		Description: "grapefruit paired with white tea and coconut milk for a balanced store-ready drink",
		Ingredients: []string{"white tea", "grapefruit", "coconut milk"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  645,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-091",
		Name:        "lychee white peppermint",
		Category:    "seasonal-4",
		Description: "lychee paired with white tea and peppermint for a balanced store-ready drink",
		Ingredients: []string{"white tea", "lychee", "peppermint"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  655,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-092",
		Name:        "passion fruit white ginger",
		Category:    "seasonal-4",
		Description: "passion fruit paired with white tea and ginger for a balanced store-ready drink",
		Ingredients: []string{"white tea", "passion fruit", "ginger"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  665,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-093",
		Name:        "pear white cinnamon",
		Category:    "seasonal-4",
		Description: "pear paired with white tea and cinnamon for a balanced store-ready drink",
		Ingredients: []string{"white tea", "pear", "cinnamon"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  675,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-094",
		Name:        "apple white honey",
		Category:    "seasonal-4",
		Description: "apple paired with white tea and honey for a balanced store-ready drink",
		Ingredients: []string{"white tea", "apple", "honey"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  685,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-095",
		Name:        "watermelon white brown sugar",
		Category:    "seasonal-4",
		Description: "watermelon paired with white tea and brown sugar for a balanced store-ready drink",
		Ingredients: []string{"white tea", "watermelon", "brown sugar"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  695,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-096",
		Name:        "hibiscus white stevia",
		Category:    "seasonal-4",
		Description: "hibiscus paired with white tea and stevia for a balanced store-ready drink",
		Ingredients: []string{"white tea", "hibiscus", "stevia"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  705,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-097",
		Name:        "peach rooibos oat",
		Category:    "seasonal-1",
		Description: "peach paired with rooibos and oat milk for a balanced store-ready drink",
		Ingredients: []string{"rooibos", "peach", "oat milk"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  620,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-098",
		Name:        "mango rooibos soy",
		Category:    "seasonal-1",
		Description: "mango paired with rooibos and soy milk for a balanced store-ready drink",
		Ingredients: []string{"rooibos", "mango", "soy milk"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  630,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-099",
		Name:        "strawberry rooibos coconut",
		Category:    "seasonal-1",
		Description: "strawberry paired with rooibos and coconut milk for a balanced store-ready drink",
		Ingredients: []string{"rooibos", "strawberry", "coconut milk"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  640,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-100",
		Name:        "lemon rooibos peppermint",
		Category:    "seasonal-1",
		Description: "lemon paired with rooibos and peppermint for a balanced store-ready drink",
		Ingredients: []string{"rooibos", "lemon", "peppermint"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  650,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-101",
		Name:        "lime rooibos ginger",
		Category:    "seasonal-1",
		Description: "lime paired with rooibos and ginger for a balanced store-ready drink",
		Ingredients: []string{"rooibos", "lime", "ginger"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  660,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-102",
		Name:        "grapefruit rooibos cinnamon",
		Category:    "seasonal-1",
		Description: "grapefruit paired with rooibos and cinnamon for a balanced store-ready drink",
		Ingredients: []string{"rooibos", "grapefruit", "cinnamon"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  670,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-103",
		Name:        "lychee rooibos honey",
		Category:    "seasonal-1",
		Description: "lychee paired with rooibos and honey for a balanced store-ready drink",
		Ingredients: []string{"rooibos", "lychee", "honey"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  680,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-104",
		Name:        "passion fruit rooibos brown sugar",
		Category:    "seasonal-1",
		Description: "passion fruit paired with rooibos and brown sugar for a balanced store-ready drink",
		Ingredients: []string{"rooibos", "passion fruit", "brown sugar"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  690,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-105",
		Name:        "pear rooibos stevia",
		Category:    "seasonal-1",
		Description: "pear paired with rooibos and stevia for a balanced store-ready drink",
		Ingredients: []string{"rooibos", "pear", "stevia"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  700,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-106",
		Name:        "apple rooibos sparkling water",
		Category:    "seasonal-1",
		Description: "apple paired with rooibos and sparkling water for a balanced store-ready drink",
		Ingredients: []string{"rooibos", "apple", "sparkling water"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  710,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-107",
		Name:        "watermelon rooibos oat",
		Category:    "seasonal-1",
		Description: "watermelon paired with rooibos and oat milk for a balanced store-ready drink",
		Ingredients: []string{"rooibos", "watermelon", "oat milk"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  720,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-108",
		Name:        "hibiscus rooibos soy",
		Category:    "seasonal-1",
		Description: "hibiscus paired with rooibos and soy milk for a balanced store-ready drink",
		Ingredients: []string{"rooibos", "hibiscus", "soy milk"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  730,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-109",
		Name:        "peach chamomile peppermint",
		Category:    "seasonal-2",
		Description: "peach paired with chamomile and peppermint for a balanced store-ready drink",
		Ingredients: []string{"chamomile", "peach", "peppermint"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  645,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-110",
		Name:        "mango chamomile ginger",
		Category:    "seasonal-2",
		Description: "mango paired with chamomile and ginger for a balanced store-ready drink",
		Ingredients: []string{"chamomile", "mango", "ginger"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  655,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-111",
		Name:        "strawberry chamomile cinnamon",
		Category:    "seasonal-2",
		Description: "strawberry paired with chamomile and cinnamon for a balanced store-ready drink",
		Ingredients: []string{"chamomile", "strawberry", "cinnamon"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  665,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-112",
		Name:        "lemon chamomile honey",
		Category:    "seasonal-2",
		Description: "lemon paired with chamomile and honey for a balanced store-ready drink",
		Ingredients: []string{"chamomile", "lemon", "honey"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  675,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-113",
		Name:        "lime chamomile brown sugar",
		Category:    "seasonal-2",
		Description: "lime paired with chamomile and brown sugar for a balanced store-ready drink",
		Ingredients: []string{"chamomile", "lime", "brown sugar"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  685,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-114",
		Name:        "grapefruit chamomile stevia",
		Category:    "seasonal-2",
		Description: "grapefruit paired with chamomile and stevia for a balanced store-ready drink",
		Ingredients: []string{"chamomile", "grapefruit", "stevia"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  695,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-115",
		Name:        "lychee chamomile sparkling water",
		Category:    "seasonal-2",
		Description: "lychee paired with chamomile and sparkling water for a balanced store-ready drink",
		Ingredients: []string{"chamomile", "lychee", "sparkling water"},
		Tags:        []string{"new-drink", "store-tested", "series-1"},
		PriceCents:  705,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-116",
		Name:        "passion fruit chamomile oat",
		Category:    "seasonal-2",
		Description: "passion fruit paired with chamomile and oat milk for a balanced store-ready drink",
		Ingredients: []string{"chamomile", "passion fruit", "oat milk"},
		Tags:        []string{"new-drink", "store-tested", "series-2"},
		PriceCents:  715,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-117",
		Name:        "pear chamomile soy",
		Category:    "seasonal-2",
		Description: "pear paired with chamomile and soy milk for a balanced store-ready drink",
		Ingredients: []string{"chamomile", "pear", "soy milk"},
		Tags:        []string{"new-drink", "store-tested", "series-3"},
		PriceCents:  725,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-118",
		Name:        "apple chamomile coconut",
		Category:    "seasonal-2",
		Description: "apple paired with chamomile and coconut milk for a balanced store-ready drink",
		Ingredients: []string{"chamomile", "apple", "coconut milk"},
		Tags:        []string{"new-drink", "store-tested", "series-4"},
		PriceCents:  735,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-119",
		Name:        "watermelon chamomile peppermint",
		Category:    "seasonal-2",
		Description: "watermelon paired with chamomile and peppermint for a balanced store-ready drink",
		Ingredients: []string{"chamomile", "watermelon", "peppermint"},
		Tags:        []string{"new-drink", "store-tested", "series-5"},
		PriceCents:  745,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
	{
		ID:          "template-120",
		Name:        "hibiscus chamomile ginger",
		Category:    "seasonal-2",
		Description: "hibiscus paired with chamomile and ginger for a balanced store-ready drink",
		Ingredients: []string{"chamomile", "hibiscus", "ginger"},
		Tags:        []string{"new-drink", "store-tested", "series-6"},
		PriceCents:  755,
		ServingNote: "shake consistently and serve at the selected sweetness level",
	},
}

func Templates() []DrinkTemplate {
	out := append([]DrinkTemplate{}, drinkTemplates...)
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}
func Template(id string) (DrinkTemplate, bool) {
	for _, item := range drinkTemplates {
		if item.ID == id {
			return item, true
		}
	}
	return DrinkTemplate{}, false
}
func SearchTemplates(query string, maxPrice int) []DrinkTemplate {
	query = strings.ToLower(strings.TrimSpace(query))
	out := []DrinkTemplate{}
	for _, item := range drinkTemplates {
		if maxPrice > 0 && item.PriceCents > maxPrice {
			continue
		}
		text := strings.ToLower(item.Name + " " + item.Description + " " + strings.Join(item.Tags, " "))
		if query == "" || strings.Contains(text, query) {
			out = append(out, item)
		}
	}
	return out
}
func InstantiateTemplate(id, recordID string) (domain.BeverageRecord, error) {
	item, ok := Template(id)
	if !ok {
		return domain.BeverageRecord{}, fmt.Errorf("template %s not found", id)
	}
	return domain.BeverageRecord{ID: recordID, Name: item.Name, Category: item.Category, Description: item.Description, Ingredients: append([]string{}, item.Ingredients...), Tags: append([]string{}, item.Tags...), PriceCents: item.PriceCents}, nil
}
